version: 1
upload:
  - source: canonical/grafana-rock
    commit: acb0ed80cef195e8f26d69f57a0995ea6b948119
    directory: 12.4.2
    release:
      12-24.04:
        end-of-life: '2026-07-07T00:00:00Z'
        risks:
          - stable
      12.4-24.04:
        end-of-life: '2026-07-07T00:00:00Z'
        risks:
          - stable
      12.4.2-24.04:
        end-of-life: '2026-04-09T00:00:00Z'
        risks:
          - stable
